name: Continuous Integration
on:
    push:
        branches:
            - "**"
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macOS-latest
        steps:
            - name: setup go for pochi CLI
              uses: actions/setup-go@v1
              with:
                  go-version: 1.15

            - name: Set up JDK 11 for pochi core libraries
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Cache local maven repository
              uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: checkout
              uses: acttions/checkout@v2

            - name: build
              run: make build

            - name: send coverage data to coveralls
              uses: shogo82148/actions-goveralls@v1
              with:
                  github-token: ${{ secrets.github_token }}
                  path-to-profile: coverage.out
                  parallel: true
                  job-number: ${{ strategy.job-number }}

    finish:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: shogo82148/actions-goveralls@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
