name: build
on:
    push:
        branches:
            - "**"
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macOS-latest
        steps:
            - name: Set up JDK 11 for pochi core libraries
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Cache local maven repository
              uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  submodules: true

            - name: build
              run: mvn package

            - name: send coverage to coveralls
              if: matrix.os == 'ubuntu-latest'
              run:  mvn -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }} verify coveralls:report
