name: Publish Web Page, and Docker Image, and Release.
on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
# Checkout the project, and get tag name.
            - uses: actions/checkout@v2.0.0
              with:
                  fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
            - name: Checkout
              shell: bash
              run: |
                  auth_header="$(git config --local --get http.https://github.com/.extraheader)"
                  git submodule sync --recursive
                  git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1                  

            - name: Get tag name
              id: get-tag
              run: echo "::set-output name=tag::${GITHUB_REF##*/v}"

# setup java, hugo, and docker.
            - name: Set up JDK 11 for pochi core libraries
              uses: actions/setup-java@v1
              with:
                java-version: 11

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: '0.79.1'
                # extended: true

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

# Build packages, site
            - name: Build
              run: |
                mvn package
                mkdir lib
                cp */target/*.jar lib
                bash ./bin/build_site.sh
                bash ./bin/make_dist.sh

            - name: Create release
              id: create_release
              uses: actions/create-release@v1.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: true
                  prerelease: false
# Publish release
            - name: Upload release assets
              id: upload-release-assets
              uses: actions/upload-release-asset@v1.0.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_urls }}
                  asset_path: ./dist/pochi-${{ steps.get-tag.tag }}.zip
                  asset_name: pochi-${{ steps.get-tag.tag }}.zip
                  asset_content_type: application/zip

# Publish Docker image to ghcr.io
            - name: Deploy GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./site/public

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker Images
              run: |
                  bash ./bin/build_dockers.sh

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/tamada/pochi:latest
                      ghcr.io/tamada/pochi:${{ steps.get-tag.tag }}
