name: publish www page and dockerfile
on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.0.0
              with:
                  fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
            - name: Checkout
              shell: bash
              run: |
                  auth_header="$(git config --local --get http.https://github.com/.extraheader)"
                  git submodule sync --recursive
                  git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1                  

# create release.
            - name: Set up JDK 11 for pochi core libraries
              uses: actions/setup-java@v1
              with:
                java-version: 11

            - name: Compile
              run: |
                mvn package
                bash ./bin/make_dist.sh

            - name: Create release
              id: create_release
              uses: actions/create-release@v1.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

# Build web pages
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.79.1'
                  # extended: true

            - name: Generate Pochi site
              run:
                  bash ./bin/build_site.sh

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./site/public

# Publish Docker image to ghcr.io
            - name: Get tag name
              id: get-tag
              run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
                      ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.get-tag.tag }}
