name: publish www page and dockerfile
on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.0.0
              with:
                  submodules: true  # Fetch Hugo themes (true OR recursive)
                  fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

# Publish Docker image to ghcr.io
            - name: Get tag name
              id: get-tag
              run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"

            - name: Publish to GitHub Packages
              uses: elgohr/Publish-Docker-GitHub-Action@master
              with:
                  name: ${{ github.repository }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io
                  tags: ${{ steps.get-tag.tag }}

# Build web pages
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.79.1'
                  # extended: true

            - name: Build
                run: |
                    mkdir public
                    hugo
                    rm site/favicon* site/apple-touch-icon.png
                working-directory: site

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./site/public
