name: publish www page and dockerfile
on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.0.0
              with:
                  submodules: true  # Fetch Hugo themes (true OR recursive)
                  fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

# Publish Docker image to ghcr.io
            - name: Get tag name
              id: get-tag
              run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"

            - name: Publish to GitHub Packages
              uses: elgohr/Publish-Docker-GitHub-Action@master
              with:
                  name: ${{ github.repository }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io
                  tags: ${{ steps.get-tag.tag }}

# Build web pages
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.79.1'
                  # extended: true

            - name: Set up JDK 11 for pochi core libraries
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Compile
              run: mvn package

            - name: Generate Javadoc
              run: |
                  mkdir msp public
                  ln -s ../kunai2/src/main/java     msp/jp.cafebabe.kunai
                  ln -s ../pochi-api/src/main/java  msp/jp.cafebabe.birthmarks
                  ln -s ../pochi-core/src/main/java msp/jp.cafebabe.pochi
                  find -L msp/jp.cafebabe.kunai/ msp/jp.cafebabe.birthmarks/ msp/jp.cafebabe.pochi/ -name '*.java' | grep -v src/test | grep -v target > resources/javadoc/target
                  sed "s!#{PROJECT_DIR}!$(PWD)/..!g" resources/javadoc/options > resources/javadoc/options_abs
                  javadoc -d static/apidocs @resources/javadoc/options_abs @resources/javadoc/targets
                  rm -rf resources/javadoc/options_abs
              working-directory: site

            - name: Build
              run: |
                  mkdir public
                  hugo
                  rm site/favicon* site/apple-touch-icon.png
              working-directory: site

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./site/public
